### ISSUE TITLE
BGP session not established

### ISSUE THREAD

**Issue by ognjen011** [Showmax/arista-eos-exporter#3]
I am picking up a weird problem i have one BGP session on one of the arista's showing not established but the show ip bgp summary defiantly shows it as up. 

In Prometheus i see it as:

arista_bgp_peer_state_info{asn="65000", instance="SW01", job="arista_exporter", peer="100.64.0.4", router_id="100.64.0.5", state="NotNegotiated", vrf="default"}

If i turn on the debug in config file both bgp sessions are up according to the output:

DEBUG eapilib.py:447 Response content: b'{"jsonrpc": "2.0", "id": "139838480148072", "result": [{"vrfs": {"default": {"routerId": "100.64.0.5", "peers": {"100.64.0.4": {"msgSent": 36718, "inMsgQueue": 0, "prefixReceived": 21, "upDownTime": "1611930496.000000", "version": 4, "prefixAccepted": 21, "msgReceived": 14713, "peerState": "Established", "outMsgQueue": 0, "underMaintenance": false, "asn": "65000"}, "100.64.0.3": {"msgSent": 759490, "inMsgQueue": 0, "prefixReceived": 19, "upDownTime": "1611930368.000000", "version": 4, "prefixAccepted": 19, "msgReceived": 7371616, "peerState": "Established", "outMsgQueue": 0, "underMaintenance": false, "asn": "65000"}}, "vrf": "default", "asn": "65003"}}}]}'

Any help would be appreciated. I have also bumped Prometheus to 2.24.1 and still seeing the same thing. Everything else behaves as it should be.

**Comment by ognjen011** [comment]
turns out it was ipv6 issue.

**Comment by zloo** [comment]
@ognjen011 could you please elaborate on what was the cause in case anyone else finds this issue? :)

**Comment by ognjen011** [comment]
IPv6 was in Established(NonNegotiated) mode. It was one of the sessions that i did not remove. After digging through the debug logs i noticed that the values were also pulled for the ipv6 not just ipv4  which was causing the alarm to trigger.
